version = "0.0.01"
    ObseritePrime = 10
    choosiumR = 20
    choosiumY = 30
    choosiumB = 40
    ChoosiumT = 75
    ReallyEpicChoosum = 101
    ReallyEpicChoosumO = 999
    CIRCLE = 252
    choosiumO = ((choosiumY * 25)+(choosiumR * 25))
    choosiumOprime = ((ObseritePrime * 2)+(choosiumO))
    choosiumG = ((choosiumR)+(choosiumY))
    choosiumP = ((choosiumR)+(choosiumB))
    HelpMe = CIRCLE + ReallyEpicChoosum
